### PR TITLE
Add option to set TLS version

### PR DESCRIPTION
**Pull request by jcavar**

### CODE REVIEW

**Comment by JackLeo** [comment]
This is meant to be configurable right?

**Comment by jcavar** [comment]
Yes, that is correct.

**Comment by JackLeo** [comment]
So you can set property `streamSSLLevel` of `MQTTCFSocketTransport` to what you want. I am just wondering if there is enough info in the comments there for people to figure this one out or should we start thinking at some spare time about handling docs for this

**Comment by JackLeo** [comment]
Also I thought github would link this PR to https://github.com/novastone-media/MQTT-Client-Framework/issues/423

**Comment by jcavar** [comment]
You are actually right, I will list possible values in header doc.

**Comment by jcavar** [comment]
I am now thinking about leaving `kCFStreamSocketSecurityLevelNegotiatedSSL` as default value because that is what it was before. Would that make more sense?

**Comment by JackLeo** [comment]
This is "whatever server is using"?

**Comment by JackLeo** [comment]
Also what's up with the broken build?

**Comment by jcavar** [comment]
Kind of:

> Specifies that the highest level security protocol that can be negotiated be set as the security protocol for a socket stream.

**Comment by jcavar** [comment]
Some flaky tests doing a lot of stuff. I will need to investigate that separately.

**Comment by JackLeo** [comment]
Yes, then `kCFStreamSocketSecurityLevelNegotiatedSSL` should be a default one. In this/next year we'll start to see wider adoption of `TLSv1.3` as well so we should not prescribe a specific version but use the best one possible.

**Comment by JackLeo** [comment]
Regards tests, we can speak to that at some other time, maybe I am just reading the logs wrong :) is there a bug # for that I could subscribe to?

**Comment by jcavar** [comment]
It is https://github.com/novastone-media/MQTT-Client-Framework/issues/414

**Comment by JackLeo** [comment]
But it is not because of missing submodules? As I read it, all tests that were run have passed

**Comment by jcavar** [comment]
No, in this case something is weird with output, it is cut off as far as I can tell.

**Pull request merged**
