### PR TITLE
Fixed crash caused by multithreading

### PR DESCRIPTION
**Pull request by CoderJJMa**
Fixed crash caused by multithreading

### CODE REVIEW

**Comment by jcavar** [comment]
Can you please provide more details about crash? Is it reproducible, is it possible to add test for this condition?

**Comment by CoderJJMa** [comment]
> 你能提供关于崩溃的更多细节吗？它是否可重复，是否可以为此条件添加测试？

sorry， Ignore this branch， my mistake， it is Still  carsh，the reason is  The zombie object，but ,i can find how to make this. if you have good idea ,please tell me. my version is 0.15.2, The probability of a crash is high

**Comment by CoderJJMa** [comment]
> 你能提供关于崩溃的更多细节吗？它是否可重复，是否可以为此条件添加测试？

crash

**Comment by jcavar** [comment]
Which version of this library are you running on?

**Comment by CoderJJMa** [comment]
> 您运行的是哪个版本的库？

version : 0.15.2

**Pull request closed without merging**
